# The URL the site will be built for
base_url = "https://spaghettitattoo.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Spaghetti Tattoo Shop"
description = "Il sito ufficiale di Spaghetti Tattoo Shop"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
instagram_url = "https://www.instagram.com/spaghettitattooshop/"
facebook_url = "https://www.facebook.com/profile.php?id=100091646377821"
google_maps_url = "https://goo.gl/maps/6QbQUFkCMJTzhmQA6"
