name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    env: {}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.0

      - name: Ensure the website builds
        uses: shalzz/zola-deploy-action@v448f43557d06624a326567089b8965c79ba58306
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

  # Following https://www.getzola.org/documentation/deployment/github-pages/
  build:
    name: Build and deploy GitHub Pages
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.0.0

      - name: Build with Zola and push to GitHub Pages
        uses: shalzz/zola-deploy-action@448f43557d06624a326567089b8965c79ba58306
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
